string cadena = "Hola mundo";
string cadena2 = cadena;
cadena = "Hola programdores\n\"Mensaje de bienvenida\"";
string ruta = @"C:\Usuarios\Marcos\Documentos"; //"C:\\Usuarios\\Marcos\\Documentos";
int programadores = 10;
decimal sueldo = 105000.5m;
string comunidad = $"Exiten {programadores} programadores en la comunidad que ganan {sueldo:C}";
int tamanio = ruta.Length;
string nombre = "   Marcos   Hernandez      ";
Console.WriteLine(cadena);
Console.WriteLine(cadena2);
Console.WriteLine(ruta);
Console.WriteLine(comunidad);
Console.WriteLine("El tamaño de la cadena ruta es {0}",tamanio);
Console.WriteLine("metodos de string");
Console.WriteLine(nombre);
Console.Write(nombre.Trim());
Console.WriteLine("Find de la impresión");
Console.WriteLine(nombre.Substring(3, 6));
Console.WriteLine(nombre.StartsWith("   M"));
Console.WriteLine(nombre.Contains("Hernandez"));
Console.WriteLine(nombre.Replace('a', 'e'));
Console.WriteLine(nombre.Trim().ToLower());
Console.WriteLine(nombre.Trim().ToUpper());
Console.ReadKey();